### ISSUE TITLE
Const localazation

### ISSUE THREAD

**Issue by trofort** [DOKononov/NoteMe#6]
Раз уж решил сделать локализацию через константы, то:
1) LoginVC - плохое название, ты его используешь и в регистрации и восстановлении пароля, мб уже назови Auth
2) Будет много строк переводимых и твой этот файл разрастется, лучше в папке Const, создай папку Localizations, и для каждой подгруппы ключей создавай новый файл

https://github.com/DOKononov/NoteMe/blob/5643b50733f1776d05a902966f4fd4bbf849ed0c/NoteMe/Utils/String%2Blocalized.swift#L21

**Comment by DOKononov** [comment]
done
